ezsystems/ezplatform-graphql

.php_cs, composer.json
> JIRA: https://jira.ez.no/browse/EZP-30200
This PR adds php-cs-fixer dependency as well as our common code style. Given there are 6 open PR we should do the code refactoring once they are all merged to avoid conflicts hell.
=> EZP-30200: Add php-cs-fixer configuration to ezplatform-graphql

README.md, TODO.md, spec/EzSystems/EzPlatformGraphQL/GraphQL/Resolver/DomainContentResolverSpec.php, spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/Worker/ContentType/AddContentOfTypeConnectionToDomainGroupSpec.php, src/GraphQL/InputMapper/SearchQueryMapper.php, src/GraphQL/Relay/DomainConnectionBuilder.php, src/GraphQL/Relay/NodeResolver.php, src/GraphQL/Relay/SearchResolver.php, src/GraphQL/Resolver/SearchResolver.php, src/Resources/config/graphql/Content.types.yml, src/Resources/config/graphql/DomainContent.types.yml, src/Resources/config/graphql/Node.types.yml, src/Resources/config/graphql/Platform.types.yml, src/Resources/config/graphql/Repository.types.yml, src/Resources/config/graphql/Search.types.yml, src/Resources/config/resolvers.yml, src/Resources/config/services.yml, src/Schema/Builder/Input/Field.php, src/Schema/Builder/Input/Type.php, src/Schema/Builder/SchemaBuilder.php, src/Schema/Domain/Content/NameHelper.php, src/Schema/Domain/Content/Worker/ContentType/AddContentOfTypeConnectionToDomainGroup.php, src/Schema/Domain/Content/Worker/ContentType/DefineDomainContent.php, src/Schema/Domain/Content/Worker/ContentType/DefineDomainContentConnection.php
Changes lists of content items to [Connections](https://facebook.github.io/relay/graphql/connections.htm):
```
{
content {
blogPosts(sortBy: DatePublished, last: 5) {
pageInfo {
hasNextPage
}
edges {
cursor
node {
title
}
}
}
}
}
```
Allows to implement [pagination](https://facebook.github.io/relay/docs/en/pagination-container.html), as well as individual items refetching.
=> Relay connections support

src/Resources/config/graphql/Field.types.yml
> Fixes [EZP-30278](https://jira.ez.no/browse/EZP-30278)
There was a typo in the field's name, now fixed.
=> Fixed ezmedia fieldtype width property (EZP-30278)

src/DependencyInjection/Compiler/FieldValueTypesPass.php, src/DependencyInjection/Compiler/RegisterSchemaDirectoryParametersPass.php, src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php, src/EzSystemsEzPlatformGraphQLBundle.php
Previously compiler passes were relying on relative paths to access schema definitions generated in `app/config/graphql/ezplatform` directory. This wasn't really working when symlinks were used during development. I think symlinks are still the best method when working with multiple packages so I couldn't align on my side to overcome this issue.
I have a proposal to move schema directories from constants to container parameters. It's more natural to me to store such information in the container which makes it accessible in services, extensions and compiler passes. 
I will leave it as a draft so we can validate the idea first.
=> EZP-30325: Generated schema is not being used when vendor packages are symlinked

src/GraphQL/Resolver/ObjectStateGroupResolver.php, src/GraphQL/Resolver/ObjectStateResolver.php, src/Resources/config/graphql/Content.types.yml, src/Resources/config/graphql/ObjectState.types.yml, src/Resources/config/graphql/ObjectStateGroup.types.yml, src/Resources/config/graphql/Repository.types.yml, src/Resources/config/resolvers.yml
> JIRA: https://jira.ez.no/browse/EZP-30283
It adds new fields to `_repository`:
- `objectStateGroup` (args: `id`) - fetches single Object State Group,
- `objectStateGroups` - fetches all Object State Groups,
- `objectState` (args: `id`) - fetches single Object State,
- `objectStates` (args: `groupId`) - fetches Object States assigned to Group with ID = `groupId`.
Also you can access object states from specific group (arg `groupId`) from the content , for example:
```graphql
{
content {
about(id: 2) {
_info {
states {
id,
identifier,
priority,
languageCodes,
group {
id,
identifier,
defaultLanguageCode,
languageCodes,
states {
...
}
}
}
}
}
}
}
```
I haven't added dynamic fields and types due to time constraints but this can be added in the future. Also mutations are not implemented yet.
=> EZP-30283: Implement fetching Object States in GraphQL

src/Resources/config/graphql/Content.types.yml
> Fixes [EZP-30275](https://jira.ez.no/browse/EZP-30275)
This was failing because of a missing resolver:
```
someContent {
_info {
currentVersion
}
}
```
Since the current version is exposed at the root of any content, it isn't necessary to have an explicit field for it. This PR removes it, thus fixing the bug.
=> Removed _info.currentVersion (EZP-30275)

spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/ContentDomainIteratorSpec.php, src/Schema/Domain/Content/ContentDomainIterator.php
> Fixes [EZP-30265](https://jira.ez.no/browse/EZP-30265)
Fixes a possible leak of items from the surrounding iterations.
Covered by unit test.
=> Content Domain Iterator should only yield fields from the current content type

src/Schema/Domain/Content/FieldValueBuilder/BaseFieldValueBuilder.php
> Fixes [EZP-30277](https://jira.ez.no/browse/EZP-30277)
The generated resolver expected the `value` property out of the returned value, while the value is returned directly.
=> Fixed image asset field value resolution (EZP-30277)

src/Resources/config/graphql/Field.types.yml
> Fixes https://jira.ez.no/browse/EZP-30327
Changes the type of `<ImageVariation>.lastModified` to `DateTime`.
In addition:
- described all the fields from `ImageVariation`
- added the `width` and `height` properties
- removed the `dirPath` field, as it returns the same value than `uri` at the moment.
=> Fixed ImageVariation lastModified field + other improvements

src/Resources/config/graphql/ContentType.types.yml
> Fixes [EZP-30274](https://jira.ez.no/browse/EZP-30274)
Adds the missing `description` field to content types:
```
{
content {
_types {
article {
_info {
description
french_description: description(languageCode: "fre-FR")
}
}
}
}
}
```
=> Added description field to content types (EZP-30274)

src/Resources/config/graphql/Content.types.yml, src/Schema/Domain/Content/FieldValueBuilder/RelationListFieldValueBuilder.php
A small fix, and a small change:
- `Content.relations` and `Content.reverseRelations` will now yield domain content items (e.g. ArticleContent)
- `ContentRelation.type` is now an enumeration with the available types
=> Fixed content relation value + type

doc/domain_schema.md, doc/howto/upload_binary_files.md, src/GraphQL/Mutation/UploadFiles.php, src/GraphQL/Resolver/FieldDefinitionResolver.php, src/Resources/config/graphql/ContentType.types.yml, src/Resources/config/graphql/FieldDefinition.types.yml, src/Resources/config/graphql/PlatformMutation.types.yml, src/Resources/config/graphql/Version.types.yml, src/Schema/Domain/Content/LanguagesIterator.php, src/Schema/Domain/Content/Worker/ContentType/DefineDomainContentMutation.php, src/Schema/Domain/Content/Worker/Language/AddLanguageToEnum.php
> Implements [EZP-30328](https://jira.ez.no/browse/EZP-30328)
Adds a `RepositoryLanguage` enum with the languages configured in the repository.
It is used as an argument whenever a language code is accepted/required.
```
{
content {
_types {
article {
_info {
name(language: fre_FR)
}
title {
name(language: ger_DE)
description(language: nor_NO)
}
}
}
}
}
```
```
mutation CreateBlogPost {
createBlogPost(
parentLocationId: 2,
language: fre_FR,
input: { ... }
)
}
```
=> Added a RepositoryLanguage enum type that lists the configured languages

src/GraphQL/Resolver/RichTextResolver.php, src/Resources/config/graphql/Field.types.yml, src/Resources/config/resolvers.yml
> [EZP-30190](https://jira.ez.no/browse/EZP-30190)
Renders richtext to a plaintext version, using the HTML version passed through `strip_tags()`.
=> Added plaintext output format for richtext

src/Resources/config/graphql/FieldValueInput.types.yml
> https://jira.ez.no/browse/EZP-30355
Fixes `timetring` in DateFieldInput format to `timestring`.
=> Fix EZP-30355: typo in DateFieldInput format

spec/EzSystems/EzPlatformGraphQL/GraphQL/Resolver/DomainContentResolverSpec.php, src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php, src/GraphQL/DataLoader/CachedContentLoader.php, src/GraphQL/DataLoader/CachedContentTypeLoader.php, src/GraphQL/DataLoader/ContentLoader.php, src/GraphQL/DataLoader/ContentTypeLoader.php, src/GraphQL/DataLoader/Exception/NotFoundException.php, src/GraphQL/DataLoader/RepositoryContentTypeLoader.php, src/GraphQL/DataLoader/SearchContentLoader.php, src/GraphQL/Resolver/ContentResolver.php, src/GraphQL/Resolver/DomainContentResolver.php, src/GraphQL/Resolver/ImageAssetFieldResolver.php, src/GraphQL/Resolver/ImageFieldResolver.php, src/GraphQL/Resolver/SearchResolver.php, src/GraphQL/Resolver/SelectionFieldResolver.php, src/Resources/config/graphql/DomainContent.types.yml, src/Resources/config/resolvers.yml, src/Resources/config/services/data_loaders.yml
The `CachedContentLoader` stores loader Content items to avoid reloading them from the Repository.
The execution time is [down 17%](https://blackfire.io/profiles/compare/bea2b8de-6565-4e7d-9231-d04dd33c9946/graph) on the following query, with way fewer DB/SPI cache* queries:
```
{
media {
images(sortBy: [_dateModified, _desc]) {
_url
name
image {
uri
}
caption { html5 }
}
}
}
```
* In regards to SPI cache, on a simple query of two fields from 3 articles, cache calls are down from ~500 to ~200. With a redis based cache, the impact is fairly important.
=> Use a Cached ContentLoader in DomainContentResolver

src/GraphQL/Resolver/DomainContentMutationResolver.php
There was an error on reading the published content due to the change of resolvers from  `ContentInfo` to `Content` in the optimizations feature.
=> Changed mutations to return Content instead of ContentInfo

spec/EzSystems/EzPlatformGraphQL/GraphQL/Resolver/DomainContentResolverSpec.php, src/GraphQL/Resolver/DomainContentResolver.php
> JIRA: https://jira.ez.no/browse/EZP-30414
The `RelationFieldDefinitionMapper` is used for both `ezobjectrelation` and `ezobjectrelationlist`. The resolver is also the same, but was not correctly updated for `ezobjectrelation`, making it return null in every case for it.
The resolver has been changed to always fetch multiple items, and return one or an array depending on the multiple flag.
=> EZP-30414: Relation fields aren't resolved

spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/Worker/ContentTypeGroup/AddDomainGroupToDomainSpec.php, spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroupSpec.php, spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroupTypesSpec.php, src/Schema/Domain/Content/Worker/ContentTypeGroup/AddDomainGroupToDomain.php, src/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroup.php, src/Schema/Domain/Content/Worker/ContentTypeGroup/DefineDomainGroupTypes.php
> https://jira.ez.no/browse/EZP-30420
All ContentTypeGroup workers will now ignore empty content types groups.
=> Ignore empty content types groups during generation (EZP-30420)

spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/NameHelperSpec.php, src/Schema/Domain/Content/NameHelper.php
> https://jira.ez.no/browse/EZP-30422
Changes the normalization of content types groups identifiers to transform all non alphanumeric characters to `_`. It is required on content types groups identifiers as they are actually human readable names.
=> Handle special characters in content type group (EZP-30422)

src/Schema/Domain/ImageVariationDomain.php
> JIRA: - 
`\EzSystems\EzPlatformGraphQL\Schema\Domain\ImageVariationDomain` shouldn't depend on specific ConfigResolverInterface impl.
_Bug discovered during working on https://jira.ez.no/browse/EZEE-2775_
=> ImageVariationDomain shouldn't depend on specific ConfigResolverInterface impl. 

composer.json
|      |     |
| --- | --- |
| **Target version** | `master` for eZ Platform `v3.0` |
This PR:
=>  [Composer] Prepared ezsystems dependencies for eZ Platform 3.0 release

src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php
Fixes the names of yaml files in the DI Extension to `.yaml` (renamed in https://github.com/ezsystems/ezplatform-graphql/pull/39).
=> Fixed loading of yaml files (.yaml instead of .yml)

src/Resources/config/services/mutations.yml
Typo in `mutations.yml`, `argments` instead of `arguments`.
=> Fixed a typo in mutations.yml

src/Command/GeneratePlatformSchemaCommand.php
|      |     |
| --- | --- |
| **Type** | Bug |
| **Target version** | `v1.0.2` for eZ Platform `v2.5.2 LTS` |
| **Requires** | #44 
Commit relevant for review: ef19288
The `ezplatform:graphql:generate-schema `(`\EzSystems\EzPlatformGraphQL\Command\GeneratePlatformSchemaCommand`) command relies on Repository but does not use it.
Right now it only generates warnings (introduced via ezsystems/ezpublish-kernel#2636) from time to time, when building container, so we should drop it.
**TODO**
=> EZP-30691: Dropped unused dependency from GeneratePlatformSchemaCommand

src/Resources/config/graphql/Search.types.yml
Was silently failing with Sf3, but doesn't stay silent with Sf4.
=> Removed a duplicate field definition in Search.types.yaml

spec/EzSystems/EzPlatformGraphQL/DependencyInjection/GraphQL/YamlSchemaProviderSpec.php, src/Command/GeneratePlatformSchemaCommand.php, src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php, src/DependencyInjection/GraphQL/YamlSchemaProvider.php
=> Updated master to use Symfony 4.3

src/DependencyInjection/Configuration.php
> JIRA: https://jira.ez.no/browse/EZP-30846
Since Symfony 4.3 configuration root name should be passed via constructor instead of using "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method.
More information:
* https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes
* https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config
=> EZP-30846: Dropped deprecated Symfony\Component\Config\Definition\Builder\TreeBuilder::root method calls

src/DependencyInjection/EzSystemsEzPlatformGraphQLExtension.php
In the previous overblog/graphql version, paths with types were auto-discovered.
This change makes the paths declaration explicit.
=> Added auto-configuration of types paths

src/GraphQL/DataLoader/Exception/ArgumentsException.php, src/GraphQL/DataLoader/LocationLoader.php, src/GraphQL/DataLoader/SearchLocationLoader.php, src/GraphQL/InputMapper/SearchQuerySortByMapper.php, src/GraphQL/Relay/Page.php, src/GraphQL/Relay/PageAwareConnection.php, src/GraphQL/Resolver/ContentResolver.php, src/GraphQL/Resolver/ContentThumbnailResolver.php, src/GraphQL/Resolver/DomainContentResolver.php, src/GraphQL/Resolver/LocationResolver.php, src/Resources/config/graphql/Content.types.yml, src/Resources/config/graphql/DomainContent.types.yml, src/Resources/config/graphql/Location.types.yml, src/Resources/config/graphql/Repository.types.yml, src/Resources/config/graphql/Version.types.yml, src/Resources/config/services/data_loaders.yml, src/Resources/config/services/resolvers.yml, src/Resources/config/services/services.yml
> JIRA: https://jira.ez.no/browse/EZP-30726
> Target version: 1.1 (merges to master for 2.0 release without any issue)
- Adds `Repository.location: Location` field that returns a location by id.
- Adds `Location.children` that returns a connection with the location's children
- Adds `Location.content: Content`
- Adds `ContentInfo.currentVersion: Version`
- Adds `Version.creator: User`
- Adds `Content._thumbnail: Thumbnail`
Also adds page number based pagination support using a new connection field, `LocationConnection.pages`.
Example:
```
{
_repository {
location(locationId: 2) {
pathString
children {
pages {
number
cursor
}
edges {
node {
content {
name
currentVersion {
creator {
name
}
}
}
}
}
}
}
}
}
```
=> Location by id with children support

src/DependencyInjection/GraphQL/YamlSchemaProvider.php, src/GraphQL/Resolver/DomainContentResolver.php, src/Resources/config/graphql/DomainContent.types.yml
After a content type has been added, but before the schema has been generated, trying to list
a location's sub-items that contain one of those items will error out. The typeResolver of the
DomainContent interface will return for items of those types a name that doesn't exist in the schema.
To work around that, content items of types that don't exist in the schema are mapped to an "anonymous" type, "UntypedContent". It has the properties shared by all content items (`_url`, `_name`, `thumb` etc, but not the fields.
=> Fix EZP-30957: avoid exceptions on content types not in the generated schema

src/GraphQL/Resolver/DomainContentResolver.php
In the backoffice, I have a relationlist with a specific order. I hope to recover my relationlist with the same order in the result of my GraphQL query.
=> [Fix] Keeping the backoffice order in the GraphQL result of the relation list

src/GraphQL/Mutation/InputHandler/FieldType/Image.php
When uploading files through GraphQL mutation, alternativeText and name fields will not populate the new object attributes.
=> Fix mutation InputHandler field mapping for Image FieldType

src/DependencyInjection/Compiler/FieldInputHandlersPass.php, src/DependencyInjection/Compiler/InputTypesMappingPass.php, src/EzSystemsEzPlatformGraphQLBundle.php, src/Resources/config/default_settings.yml, src/Resources/config/services/mutations.yml, src/Schema/Domain/Content/Mapper/FieldDefinition/ConfigurableFieldDefinitionMapper.php
> Continuation of https://github.com/ezsystems/ezplatform-graphql/pull/61
Completes the deprecations required by https://github.com/ezsystems/ezplatform-matrix-fieldtype/pull/20. The change should be fully forward compatible.
- Moved `inputType` attributes from built-in field types input handler services, and added them to the configuration.
- When the `inputType attribute` is set on an `ezplatform_graphql.fieldtype_input_handler` tag, add it to the configuration for that field type as `input_type`.
- For every `input_type` configuration, tag the `ConfigurableFieldDefinitionMapper` as `ezplatform_graphql.field_definition_input_mapper` for that fieldtype so that it gets injected into the worker for that field type
- Implemented `FieldDefinitionInputMapper` on …
=> More deprecations in input_type configuration

src/GraphQL/Mutation/UploadFiles.php, src/GraphQL/Resolver/ContentThumbnailResolver.php, src/GraphQL/Resolver/DomainContentMutationResolver.php, src/GraphQL/Resolver/ImageFieldResolver.php, src/GraphQL/Resolver/ObjectStateGroupResolver.php, src/GraphQL/Resolver/ObjectStateResolver.php, src/Schema/Domain/Content/Worker/ContentType/AddContentOfTypeConnectionToDomainGroup.php, src/Schema/Domain/Content/Worker/ContentType/AddDomainContentToDomainGroup.php
[EZP-31021](https://jira.ez.no/browse/EZP-31021)
Main PR: https://github.com/ezsystems/ezpublish-kernel/pull/2878
=> EZP-31021: Revise exception & command microcopy

src/GraphQL/Resolver/ImageAssetFieldResolver.php
JIRA ticket: [EZP-31240](https://jira.ez.no/browse/EZP-31240)
>Currently, when CT definition is modified by adding ImageAsset FieldType and regenerating GraphQL schema, querying by objects which were created before the update ends up with an error.
=> EZP-31240: Querying for contentobjects missing ImageAsset FieldType in GraphQL ends up with an error

composer.json
> JIRA: -
`\DOMDocument` is used in few places so `ext-dom` should be declared as a dependency to `composer.json`.
=> Added missing ext-dom dependency

src/GraphQL/Mutation/InputHandler/FieldType/RichText.php, src/GraphQL/Mutation/InputHandler/FieldType/RichText/HtmlRichTextConverter.php, src/GraphQL/Mutation/InputHandler/FieldType/RichText/MarkdownRichTextConverter.php, src/GraphQL/Resolver/RichTextResolver.php
> JIRA: https://jira.ez.no/browse/EZP-30517
RichText Field Type was dropped from the Kernel code in https://github.com/ezsystems/ezpublish-kernel/pull/2659 so all `eZ\Publish\Core\FieldType\RichText\**`  imports should be updated to `EzSystems\EzPlatformRichText\eZ\RichText\**`. Otherwise, any usage of mutations will cause: 
```
Argument 1 passed to EzSystems\\EzPlatformGraphQL\\GraphQL\\Mutation\\InputHandler\\FieldType\\RichText\\HtmlRichTextConverter::__construct() must be an instance of eZ\\Publish\\Core\\FieldType\\RichText\\Converter, instance of Aggregate_f3ff3dd given, called in /Users/awojs/eZ/ezplatform-ee-3.0-beta4/var/cache/dev/ContainerQaxwiHC/getDomainContentMutationResolverService.php on line 27
```
=> EZP-30517: Dropped RichText Field Type from Kernel code

spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/ContentDomainIteratorSpec.php, src/GraphQL/Resolver/DomainContentMutationResolver.php
> JIRA: [EZP-31078](https://jira.ez.no/browse/EZP-31078)
Follow up for https://github.com/ezsystems/ezpublish-kernel/pull/2839. PR contains two related changes: 
* https://github.com/ezsystems/ezplatform-graphql/commit/947a6df1eedaae6ae108d2bf180c93aa8428d9c1 adjust PHP spec to unblock CI
* https://github.com/ezsystems/ezplatform-graphql/commit/cec4aea874c0b63e0fa0be487ddc8393e02e709d replaces `eZ\Publish\Core\Repository\Values\ContentType\ContentType::getFieldDefinitionById` method usages
=>  EZP-31078: Enhanced Content Type Value Object

spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/Worker/FieldDefinition/AddFieldValueToDomainContentSpec.php, src/Schema/Domain/Content/Mapper/FieldDefinition/ConfigurableFieldDefinitionMapper.php, src/Schema/Domain/Content/Mapper/FieldDefinition/DecoratingFieldDefinitionMapper.php, src/Schema/Domain/Content/Mapper/FieldDefinition/DefaultFieldDefinitionMapper.php, src/Schema/Domain/Content/Mapper/FieldDefinition/FieldDefinitionArgsBuilderMapper.php, src/Schema/Domain/Content/Mapper/FieldDefinition/FieldDefinitionInputMapper.php, src/Schema/Domain/Content/Mapper/FieldDefinition/FieldDefinitionMapper.php, src/Schema/Domain/Content/Mapper/FieldDefinition/ResolverVariables.php, src/Schema/Domain/Content/Worker/FieldDefinition/AddFieldValueToDomainContent.php
Merge of https://github.com/ezsystems/ezplatform-graphql/pull/76.
- merged the `FieldDefinitionArgsBuilderMapper` interface into `FieldDefinitionMapper`
- removed the compiler pass
- removed the extra argument and BC code in the `addFieldValueToDomainContent` Worker
=> Field value args mapper 2.0

src/Schema/Domain/Content/Mapper/FieldDefinition/RelationFieldDefinitionMapper.php
More details at https://jira.ez.no/browse/EZP-31597
Also, it might worth showing errors like this during the schema update, but it would require injecting the logger into the mappers.
@bdunogier
=> EZP-31597: Handled missing Content Types when generating Schema

src/Resources/config/graphql/Field.types.yml
I had issues fetching multiple image variations in a single request 
(Array to String Conversion)
Upon debugging i figured the field type resolver is wrong
=> Fixing image variations resolver

src/Resources/config/graphql/FieldDefinition.types.yaml
> JIRA: -
Exposed `eZ\Publish\API\Repository\Values\ContentType\FieldDefinition::$isThumbnail` in GraphQL
=> Exposed FieldDefinition::$isThumbnail

composer.json
Required to fix ordering issues of extensions that prepend graphql types. In v0.12 of overblog/graphqlbundle, the types definitions aren't handled with a container extension anymore, but with a compiler pass.
=> Upgraded overblog/graphql-bundle to v0.12

src/GraphQL/Resolver/DomainContentMutationResolver.php
Jira ticket: https://issues.ibexa.co/browse/EZP-32256
Shortly, this PR address 3 issues with validation
- `$fieldErrors['eng-GB']` is not an array, but single error
- use translated message text instead of `Value for required field definition '%identifier%' with language '%code%' is empty"`
- undefined index 'eng-GB' if no such language in the system
*STR:*
1. On clean install, replace `eng-GB` language to `eng-US`. You can use SQL to speed it up (instead of doing it manually in admin):
```
UPDATE `ezcontentclass`
SET `serialized_name_list` = REPLACE(`serialized_name_list`, "eng-GB", "eng-US")
WHERE `serialized_name_list` LIKE "%eng-GB%";
UPDATE `ezcontentclass`
SET `serialized_description_list` = REPLACE(`serialized_description_list`, "eng-GB", "eng-US")
WHERE …
```
=> EZP-32256: GraphQL field validation throws exception without 'eng-GB' language

src/GraphQL/Resolver/ContentThumbnailResolver.php
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-32379](https://issues.ibexa.co/browse/EZP-32379)
| **Type**                                   | bug
| **Target eZ Platform version** | v3.2
| **BC breaks**                          | no
| **Doc needed**                       | no
As for now, thumbnails are not generated based on 'ezobjectrelation' field type. There is no such strategy (unlike for 'Image' or 'ImageAsset' - `ezplatform-kernel/eZ/Publish/SPI/Repository/Strategy/ContentThumbnail/Field/FieldTypeBasedThumbnailStrategy`), therefore the "is Thumbnail" field is disabled in case of 'ezobjectrelation'.
This PR fixes the infinite loop originating from the circular …
=> EZP-32379: Deleted unusable thumbnail generation based on 'ezobjectrelation'

spec/EzSystems/EzPlatformGraphQL/Schema/Domain/Content/NameHelperSpec.php, src/Resources/config/default_settings.yaml, src/Resources/config/services/services.yaml, src/Schema/Domain/Content/NameHelper.php
This PR adds an option to define field name overrides to avoid issues like:
https://issues.ibexa.co/browse/EZP-32261
=> EZP-32261: Added field name override

src/GraphQL/Resolver/ContentThumbnailResolver.php, src/Resources/config/graphql/DomainContent.types.yaml, src/Resources/config/services/resolvers.yaml
https://issues.ibexa.co/browse/IBX-354
frontend part adjustments: 
https://github.com/ezsystems/ezplatform-admin-ui/pull/1756
=> IBX-354: Used thumbnail strategy for thumbnail generation

src/GraphQL/Resolver/DomainContentResolver.php, src/Schema/Domain/Content/Mapper/FieldDefinition/ResolverVariables.php, src/Schema/Domain/Content/Worker/FieldDefinition/AddFieldValueToDomainContent.php
| Question                                  | Answer
| ----------------------------------------- | ------------------
| **JIRA issue**                            | https://issues.ibexa.co/browse/IBX-1130
| **Type**                                  | feature
| **Target Ibexa DXP version**              | `v3.3.10` 
| **BC breaks**                             | no 
New version of #56 for the 2.3 branch.
Gives more flexibility when querying multilingual content. As long as the current siteaccess is configured with several (or all) languages, multiple translations of each field can be obtained at once.
When no language is specified, the previous behaviour is maintained, and the most prioritized existing translation is used.
=> IBX-1130: Add language argument to translatable fields
